### ISSUE TITLE
LCD graphics are distorted

### ISSUE THREAD

**Issue by Gradimilo** [Creality3DPrinting/Ender-3#13]
I download the firmware and I use de arduino IDE to upload de files to ender 3, but the LCD screen are distorted and its almost impossible to read the lines. I tried others IDE versions, others u8glib versions and nothing has work.

At others Marlins versions (news) the LCD works fine.

**Comment by bmcdaniel74** [comment]
I have the same issue. Has anyone else experienced this?

**Comment by Snakefreak** [comment]
I have a Workaround remove the LCD with bezel. Try out. Mount mine with pla printed bolts and washers.

**Comment by tkuan** [comment]
I just want to post this solution for anyone has scrambled LCD problem. I got it resolved by commenting out #pragma GCC optimize (3) in ultralcd_st7920_u8glib_rrd.h file.

**Comment by steenerson** [comment]
Thanks for posting the fix, I believe this was fixed by an arduino/library/firmware update along the way as it works now without that line commented out. Closing out this old issue.

**Comment by tkuan** [comment]
Sent from Yahoo Mail for iPhone


On Friday, December 13, 2019, 1:06 AM, steenerson <notifications@github.com> wrote:


Thanks for posting the fix, I believe this was fixed by an arduino/library/firmware update along the way as it works now without that line commented out. Closing out this old issue.
